export enum RightsStatus {
  SAFE_REUSE = "SAFE_REUSE",
  ATTRIBUTION_REQUIRED = "ATTRIBUTION_REQUIRED",
  REVIEW_REQUIRED = "REVIEW_REQUIRED",
  REFERENCE_ONLY = "REFERENCE_ONLY",
  BLOCKED = "BLOCKED",
}

export enum MediaType {
  IMAGE = "IMAGE",
  VIDEO = "VIDEO",
  AUDIO = "AUDIO",
}

export enum QueryType {
  OFFICIAL = "OFFICIAL",
  EVENT = "EVENT",
  COMPANY = "COMPANY",
  PERSON = "PERSON",
  LOCATION = "LOCATION",
  CONCEPT = "CONCEPT",
  BROLL = "BROLL",
}
